In [1]:
import numpy as np
from cffi.cffi_opcode import PRIM_INT

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [12]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr =np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr = np.linspace(1,22,100)
arr

array([ 1.        ,  1.21212121,  1.42424242,  1.63636364,  1.84848485,
        2.06060606,  2.27272727,  2.48484848,  2.6969697 ,  2.90909091,
        3.12121212,  3.33333333,  3.54545455,  3.75757576,  3.96969697,
        4.18181818,  4.39393939,  4.60606061,  4.81818182,  5.03030303,
        5.24242424,  5.45454545,  5.66666667,  5.87878788,  6.09090909,
        6.3030303 ,  6.51515152,  6.72727273,  6.93939394,  7.15151515,
        7.36363636,  7.57575758,  7.78787879,  8.        ,  8.21212121,
        8.42424242,  8.63636364,  8.84848485,  9.06060606,  9.27272727,
        9.48484848,  9.6969697 ,  9.90909091, 10.12121212, 10.33333333,
       10.54545455, 10.75757576, 10.96969697, 11.18181818, 11.39393939,
       11.60606061, 11.81818182, 12.03030303, 12.24242424, 12.45454545,
       12.66666667, 12.87878788, 13.09090909, 13.3030303 , 13.51515152,
       13.72727273, 13.93939394, 14.15151515, 14.36363636, 14.57575758,
       14.78787879, 15.        , 15.21212121, 15.42424242, 15.63

In [10]:
arr = np.arange(1,25).reshape((4,6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [12]:
np.vsplit(arr,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [13]:
np.hsplit(arr,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [70]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [72]:
np.sum(s,axis=1)


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [71]:
np.sum(s,axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [75]:
slice = s[0:3,0:3]
slice

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [76]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [65]:
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [16]:
s.shape

(9, 9)

In [17]:
data.shape

(5, 3)

In [77]:
age= np.mean(data[:,0])
age

np.float64(18.4)

In [47]:
Maths = data[:,1]
Maths

array([85, 92, 76, 65, 90])

In [28]:
Science = data[:,2]
Science.max()

np.int64(95)

In [34]:
Maths += 5
Maths

array([90, 97, 81, 70, 95])

In [42]:
age = data[:,0]
Bool_index = age <= 19
Bool_index
age = len(age[Bool_index])
age

4

In [48]:
Maths = Maths.sum() / len(Maths)
Maths


np.float64(81.6)

In [50]:
Science = data[:,2]
Science = Science.sum() / len(Science)
Science

np.float64(83.2)

In [68]:

bool_idx = (data[:,2] >= 80) & (data[:,1] >= 80)
Student =data[bool_idx]
Student

array([[19, 92, 88],
       [20, 90, 85]])

In [69]:
Maths = data[:,1]
bool_ind = Maths >= 80
Maths=Maths[bool_ind]
Maths.size

3

In [64]:
Science = data[:,2]
for i in range(len(Science)):
    if Science[i] < 75:
        Science[i] = 0
Science

array([78, 88, 95,  0, 85])